[tool.poetry]
name = "jangki-proto"
version = "0.1.0"
description = ""
authors = ["yangroro <yang@heechan.kr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
jupyterlab = "^4.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
